add_newline = false

# Template for custom format
# format = """
# [┌───────────────────>](bold green)
# [│](bold green)$directory$rust$package
# [└─>](bold green) """

show_always=true

format = """
[╭─❰](bold blue) $hostname$git_branch$git_status[❱─❰](bold blue)$directory[\b❱](bold blue)$character
[╰──╼](bold blue)[ \\$ ](bold)"""

[directory]
read_only = " readonly"
read_only_style = "bold red"
truncation_length = 5

[hostname]
disabled = false
ssh_only = false
format = "[$hostname]($style)"
style = "bold"

[character]
success_symbol = ""
error_symbol = "[─❰](bold blue)[-](bold red)[❱](bold blue)"

[line_break]
disabled = true

[package]
disabled = true

[git_branch]
format = " on [$symbol$branch]($style)"

[git_status]
format = ' ([\($all_status$ahead_behind\)]($style))'
style = "bold yellow"
